// Writes src/environments/environment.generated.ts from build-time environment variables.
// Runs before every build (npm "prebuild"), including on Vercel.
//
// Only the public API URL belongs here. Authentication and data stay in the Render backend.
import { mkdirSync, writeFileSync } from 'node:fs';

const env = process.env;
const apiBaseUrl = (env.NG_APP_API_BASE_URL ?? '').trim().replace(/\/+$/, '');
const production = env.VERCEL === '1' || env.NODE_ENV === 'production' || env.NG_APP_REQUIRE_CONFIG === '1';

function fail(message) {
  console.error(`write-env: ${message}`);
  process.exit(1);
}

if (/password=|pwd=/i.test(apiBaseUrl)) {
  fail('A connection string was supplied where a URL was expected.');
}
if (production) {
  if (apiBaseUrl && !/^https:\/\//.test(apiBaseUrl)) fail('NG_APP_API_BASE_URL must be the https URL of the Render backend.');
}

const config = {
  apiBaseUrl: apiBaseUrl || (production ? 'https://authbridge-api.onrender.com' : 'http://localhost:5243'),
  authMode: production ? 'demo' : 'localDev',
};

const generatedFile = new URL('../src/environments/environment.generated.ts', import.meta.url);
mkdirSync(new URL('../src/environments/', import.meta.url), { recursive: true });
writeFileSync(
  generatedFile,
  `// Generated by scripts/write-env.mjs at build time. Do not edit or commit.\n` +
    `import type { AppConfig } from '../app/core/config';\n\n` +
    `export const generatedConfig: AppConfig = ${JSON.stringify(config, null, 2)};\n`,
);
console.log(`write-env: authMode=${config.authMode} api=${config.apiBaseUrl}`);
