// Writes src/environments/environment.generated.ts from build-time environment variables.
// Runs before every build (npm "prebuild"), including on Vercel.
//
// Only public values belong here: the API URL, the Supabase project URL and the Supabase
// publishable (anon) key. The build fails if a value looks like a secret or service-role key,
// because anything in this file ships to every browser.
import { writeFileSync } from 'node:fs';

const env = process.env;
const apiBaseUrl = (env.NG_APP_API_BASE_URL ?? '').trim().replace(/\/+$/, '');
const supabaseUrl = (env.NG_APP_SUPABASE_URL ?? '').trim().replace(/\/+$/, '');
const supabaseKey = (env.NG_APP_SUPABASE_PUBLISHABLE_KEY ?? '').trim();
const production = env.VERCEL === '1' || env.NODE_ENV === 'production' || env.NG_APP_REQUIRE_CONFIG === '1';

function fail(message) {
  console.error(`write-env: ${message}`);
  process.exit(1);
}

function jwtRole(token) {
  const parts = token.split('.');
  if (parts.length !== 3) return null;
  try {
    return JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8')).role ?? null;
  } catch {
    return null;
  }
}

if (supabaseKey.startsWith('sb_secret_') || jwtRole(supabaseKey) === 'service_role') {
  fail('NG_APP_SUPABASE_PUBLISHABLE_KEY is a secret/service-role key. Use the publishable key; secrets stay on the backend.');
}
if (/password=|pwd=/i.test(`${apiBaseUrl}${supabaseUrl}`)) {
  fail('A connection string was supplied where a URL was expected.');
}
if (production) {
  if (!/^https:\/\//.test(apiBaseUrl)) fail('NG_APP_API_BASE_URL must be the https URL of the Render backend.');
  if (!/^https:\/\//.test(supabaseUrl)) fail('NG_APP_SUPABASE_URL must be the https URL of the Supabase project.');
  if (!supabaseKey) fail('NG_APP_SUPABASE_PUBLISHABLE_KEY is required for a production build.');
}

const config = {
  apiBaseUrl: apiBaseUrl || 'http://localhost:5243',
  authMode: supabaseUrl && supabaseKey ? 'supabase' : 'localDev',
  supabaseUrl,
  supabasePublishableKey: supabaseKey,
};

writeFileSync(
  new URL('../src/environments/environment.generated.ts', import.meta.url),
  `// Generated by scripts/write-env.mjs at build time. Do not edit or commit.\n` +
    `import type { AppConfig } from '../app/core/config';\n\n` +
    `export const generatedConfig: AppConfig = ${JSON.stringify(config, null, 2)};\n`,
);
console.log(`write-env: authMode=${config.authMode} api=${config.apiBaseUrl}`);
